In [1]:
import torch
import numpy as np

x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
# print(x[ ,:2])

In [2]:
y = x.clone()
print(y)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [3]:
x = torch.tensor([1, 2, 3, 4, 5, 6])
print(x)
print(y)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [4]:
y = x.clone()
print(y)

tensor([1, 2, 3, 4, 5, 6])


In [3]:
c = np.random.normal(size=(5, 3, 32, 32), scale=0.5)
print(c.shape)
print(c[0, 0])

(5, 3, 32, 32)
[[ 0.14830352 -0.21266561  0.01777154 ...  0.06920759 -0.4629474
   0.21809094]
 [ 0.19011722 -0.74003142 -0.2885477  ... -0.01809521  0.40215148
   0.24969908]
 [-0.36672183  0.39514651  0.59343463 ...  0.26635863  0.22649837
  -0.78784752]
 ...
 [-0.44448822 -0.17705339  0.25750024 ... -0.66773184  0.03636415
   0.77332558]
 [-0.37484877 -0.36799779 -0.31815551 ...  0.80750287  0.62947635
   0.17236345]
 [-0.40315884 -0.03500245  0.42613244 ... -0.33561312  0.05277375
  -0.10226377]]


In [8]:
print(x.view(-1))

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [16]:
import pickle
f_name = 'test.pkl'
f = open(f_name, 'wb')
pickle.dump(x, f)

ValueError: binary mode doesn't take an encoding argument

In [4]:
import pickle
f = open('demo.pckl', 'rb')
output, list_softmax, target = pickle.load(f)
print(f'list_softmax: {list_softmax[1].shape}')
print(f'output: {len(list_softmax)}')
print(f'output: {output.shape}')
print(f'target: {target.size()}')


list_softmax: (10,)
output: 10000
output: torch.Size([16, 10])
target: torch.Size([16])


In [6]:
import torch.nn.functional as F
F.softmax(output).shape

C:\Users\10520\AppData\Local\Temp\ipykernel_15492\3446403210.py:2: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(output).shape


torch.Size([16, 10])

In [61]:
# AURC and EAURC
softmax = np.array(list_softmax)
correctness = np.array(list_correct)

softmax_max = np.max(softmax, axis=1)
print(f'softmax_max: {softmax_max.shape}')

sort_values = sorted(zip(softmax_max, correctness), key=lambda x: x[0], reverse=True)
print(f'sort_values: {sort_values}')

softmax_max: (10000,)
sort_values: [(0.9729567, 1), (0.96805453, 1), (0.9612562, 1), (0.9596593, 1), (0.95695823, 1), (0.95565534, 1), (0.9552142, 1), (0.9536133, 1), (0.9528613, 1), (0.9525989, 1), (0.9520472, 1), (0.95143485, 1), (0.950683, 1), (0.9491667, 1), (0.9489654, 1), (0.94634134, 1), (0.9461887, 1), (0.94516927, 1), (0.9450314, 1), (0.9426834, 1), (0.942144, 1), (0.9406143, 1), (0.9403387, 1), (0.9389268, 1), (0.9385478, 1), (0.9374067, 1), (0.93719465, 1), (0.9365731, 1), (0.93563503, 1), (0.9352266, 1), (0.9333406, 1), (0.9328994, 1), (0.9310238, 1), (0.929556, 1), (0.92890394, 1), (0.9285862, 0), (0.9285266, 1), (0.92739594, 1), (0.9266344, 1), (0.92505944, 1), (0.9248123, 1), (0.9244455, 1), (0.9227826, 1), (0.92274463, 1), (0.92254627, 0), (0.9214169, 1), (0.92064875, 0), (0.92055166, 1), (0.9202695, 1), (0.9197433, 0), (0.9194073, 1), (0.91922325, 1), (0.91909647, 1), (0.91884464, 1), (0.91854715, 1), (0.9183875, 1), (0.9176, 1), (0.91727406, 1), (0.916876, 1), (0.9164

In [62]:
sort_softmax_max, sort_correctness = zip(*sort_values)
print(f'sort_softmax_max: {sort_softmax_max}')
print(f'sort_correctness: {sort_correctness}')

sort_softmax_max: (0.9729567, 0.96805453, 0.9612562, 0.9596593, 0.95695823, 0.95565534, 0.9552142, 0.9536133, 0.9528613, 0.9525989, 0.9520472, 0.95143485, 0.950683, 0.9491667, 0.9489654, 0.94634134, 0.9461887, 0.94516927, 0.9450314, 0.9426834, 0.942144, 0.9406143, 0.9403387, 0.9389268, 0.9385478, 0.9374067, 0.93719465, 0.9365731, 0.93563503, 0.9352266, 0.9333406, 0.9328994, 0.9310238, 0.929556, 0.92890394, 0.9285862, 0.9285266, 0.92739594, 0.9266344, 0.92505944, 0.9248123, 0.9244455, 0.9227826, 0.92274463, 0.92254627, 0.9214169, 0.92064875, 0.92055166, 0.9202695, 0.9197433, 0.9194073, 0.91922325, 0.91909647, 0.91884464, 0.91854715, 0.9183875, 0.9176, 0.91727406, 0.916876, 0.9164475, 0.9158056, 0.9151436, 0.9150874, 0.9148844, 0.9147187, 0.9138181, 0.91345537, 0.91253483, 0.91177976, 0.91166013, 0.91098297, 0.9107181, 0.9102609, 0.9102558, 0.9098477, 0.9086828, 0.9067896, 0.9066921, 0.90658396, 0.9061314, 0.9058733, 0.905717, 0.9055167, 0.9052688, 0.9036166, 0.9036089, 0.9030411, 0.9026

In [49]:
risk_li, coverage_li = coverage_risk(sort_softmax_max, sort_correctness)
aurc, eaurc = aurc_eaurc(risk_li)

risk_list: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.027777777777777776, 0.02702702702702703, 0.02631578947368421, 0.02564102564102564, 0.025, 0.024390243902439025, 0.023809523809523808, 0.023255813953488372, 0.022727272727272728, 0.044444444444444446, 0.043478260869565216, 0.06382978723404255, 0.0625, 0.061224489795918366, 0.08, 0.0784313725490196, 0.07692307692307693, 0.07547169811320754, 0.07407407407407407, 0.07272727272727272, 0.07142857142857142, 0.07017543859649122, 0.06896551724137931, 0.06779661016949153, 0.06666666666666667, 0.06557377049180328, 0.06451612903225806, 0.06349206349206349, 0.0625, 0.07692307692307693, 0.07575757575757576, 0.07462686567164178, 0.07352941176470588, 0.07246376811594203, 0.07142857142857142, 0.08450704225352113, 0.08333333333333333, 0.0821917808219178, 0.08108108108108109, 0.08, 0.07894736842105263, 0.09090909090909

In [41]:
# coverage_risk
def coverage_risk(confidence, sort_correctness):
    confidence = sort_softmax_max
    sort_correctness

    risk_list = []
    coverage_list = []
    risk = 0

    for i in range(len(confidence)):
        # from 0 to 1
        coverage = (i + 1) / len(confidence)
        coverage_list.append(coverage)
        
        # wrong prediction
        # 错误预测占总预测的比例
        if sort_correctness[i] == 0:
            risk += 1
        
        risk_list.append(risk / (i + 1))
        
    return risk_list, coverage_list
risk_li, coverage_li = coverage_risk(sort_softmax_max, sort_correctness)


In [48]:

# 利用错误率累计曲线计算
def aurc_eaurc(risk_list):
    risk_list = risk_li
    # r is the total mistake rate
    r = risk_list[-1]
    print(f'risk_list: {risk_list}')
    risk_coverage_curve_area = 0

    # is a threshold
    optimal_risk_area = r + (1 - r) * np.log(1 - r)

    for risk in risk_list:
        risk_coverage_curve_area += risk * (1 / len(risk_list))
        

    aurc = risk_coverage_curve_area
    eaurc = risk_coverage_curve_area - optimal_risk_area

    print(f'aurc: {aurc}')
    print(f'eaurc: {eaurc}')

    print("AURC {0:.2f}".format(aurc*1000))
    print("EAURC {0:.2f}".format(eaurc*1000))
    return aurc, eaurc



In [75]:

# calc fpr auroc aupr 

def calc_fpr_aupr(list_softmax, list_correct):
    softmax_np = np.array(list_softmax)
    # print(f'softmax_np: {softmax_np.shape}')
    correctness_np = np.array(list_correct)
    # 得到每个softmax的最大值
    softmax_max_np = np.max(softmax_np, 1)
    # print(f'softmax_max_np: {softmax_max_np.shape}')
    from sklearn import metrics

    # 顺序排列后，逐个预测，计算fpr和tpr， 从socre中得到的是预测变化
    fpr, tpr, thresholds = metrics.roc_curve(correctness_np, softmax_max_np)
    print(f'fpr: {fpr.shape}')
    print(f'tpr: {tpr.shape}')
    print(f'thresholds: {thresholds.shape}')
    auroc = metrics.auc(fpr, tpr)

    idx_tpr_95 = np.argmin(np.abs(tpr - 0.95))
    print(f'idx_tpr_95: {idx_tpr_95}')
    fpr_in_tpr_95 = fpr[idx_tpr_95]
    print(f'fpr_in_tpr_95: {fpr_in_tpr_95}')
    tpr_in_tpr_95 = tpr[idx_tpr_95]
    print(f'tpr_in_tpr_95: {tpr_in_tpr_95}')

    precision, recall, thresholds = metrics.precision_recall_curve(correctness, softmax_max)
    aupr_success = metrics.auc(recall, precision)

    aupr_err = metrics.average_precision_score(-1 * correctness + 1, -1 * softmax_max)

    print("AUROC {0:.2f}".format(auroc * 100))
    print('AUPR_Success {0:.2f}'.format(aupr_success * 100))
    print("AUPR_Error {0:.2f}".format(aupr_err*100))
    print('FPR@TPR95 {0:.2f}'.format(fpr_in_tpr_95*100))

    return auroc, aupr_success, aupr_err, fpr_in_tpr_95

auroc, aupr_success, aupr_err, fpr_in_tpr_95 = calc_fpr_aupr(list_softmax, list_correct)

fpr: (4306,)
tpr: (4306,)
thresholds: (4306,)
idx_tpr_95: 3946
fpr_in_tpr_95: 0.8393867494068261
tpr_in_tpr_95: 0.9500110595001106
AUROC 70.89
AUPR_Success 67.82
AUPR_Error 71.91
FPR@TPR95 83.94


In [83]:
from sklearn import metrics
# calc_new_fpr
list_softmax
list_correct

softmax_np = np.array(list_softmax)
correctness_np = np.array(list_correct)
result = dict()
softmax_max_np = np.max(softmax_np, 1)

fpr, tpr, thresholds = metrics.roc_curve(correctness_np, softmax_max_np)

result['auroc'] = metrics.auc(fpr, tpr)

precision, recall, thresholds = metrics.precision_recall_curve(correctness_np, softmax_max_np)
result['AU_PR_POS'] = metrics.auc(recall, precision)
# print(1-y)
precision, recall, thresholds = metrics.precision_recall_curve(1 - correctness_np, -softmax_max_np)
result['AU_PR_NEG'] = metrics.auc(recall, precision)

if (softmax_max_np.max() == softmax_max_np.min()):
    result['FPR-95%-TPR'] = 0
else:
    for i, delta in enumerate(np.arange(softmax_max_np.min(),  softmax_max_np.max(), 
                                        (softmax_max_np.max() - softmax_max_np.min())/10000 )):
        tpr = len(softmax_max_np[(softmax_max_np >= delta) & (correctness_np == 1)]) / len(softmax_max_np[correctness_np == 1])
        if 0.9505 >= tpr >= 0.9495:
            fpr = len(softmax_max_np[(softmax_max_np >= delta) & (correctness_np == 0)]) / len(softmax_max_np[correctness_np == 0])
            result['FPR-95%-TPR'] = fpr
            print(delta)
            break
        else:
            result['FPR-95%-TPR'] = 0
        
for t in result:
    result[t] = round(100.0 * result[t], 2)
print('FPR@TPR95 new {0:.2f}'.format(result['FPR-95%-TPR']))



0.2561746394634302
FPR@TPR95 new 84.12


In [ ]:
# calc nll brier
# calculate the average negative log-likelihood loss 
list_softmax
list_correct






In [18]:
import torch
from torch import nn
input = torch.randn(3, 5, requires_grad=True)
target = torch.randint(5,(3,), dtype=torch.int64)

print(input)
print(target)
print(nn.CrossEntropyLoss()(input, target))

tensor([[ 0.7643,  0.0361,  0.0340,  1.6500, -0.9245],
        [-1.9838,  1.5353, -0.0108,  0.1692,  0.0821],
        [ 0.1415, -0.9097, -0.8756,  0.7816, -0.0701]], requires_grad=True)
tensor([1, 2, 4])
tensor(2.0136, grad_fn=<NllLossBackward0>)


In [19]:
x = torch.tensor([[ 0.7643,  0.0361,  0.0340,  1.6500, -0.9245],
        [-1.9838,  1.5353, -0.0108,  0.1692,  0.0821],
        [ 0.1415, -0.9097, -0.8756,  0.7816, -0.0701]])
y = torch.tensor([1, 2, 4])
prob = torch.softmax(x, dim=1)
prob2 = nn.functional.softmax(x, dim=1)
print(prob)
print(prob2)

tensor([[0.2186, 0.1055, 0.1053, 0.5301, 0.0404],
        [0.0171, 0.5775, 0.1231, 0.1473, 0.1350],
        [0.2264, 0.0791, 0.0819, 0.4294, 0.1832]])
tensor([[0.2186, 0.1055, 0.1053, 0.5301, 0.0404],
        [0.0171, 0.5775, 0.1231, 0.1473, 0.1350],
        [0.2264, 0.0791, 0.0819, 0.4294, 0.1832]])


In [23]:
en = -(torch.log(prob[0, 1])+torch.log(prob[1, 2])+torch.log(prob[2, 4]))/3
en

tensor(-2.0136)

In [21]:
x[1, 1]

tensor(1.5353)

In [7]:
import numpy as np
import pandas as pd
import os
from sklearn import metrics


import torch
import pickle
import torch.nn.functional as F
#  Reliability Diagrams

f = open('demo.pckl', 'rb')
output, _, label = pickle.load(f)
softmax = F.softmax(output)

softmax = torch.tensor(softmax)
label = torch.tensor(label)

# print(softmax)
bins = 15

bin_boundaries = torch.linspace(0, 1, bins + 1)
bin_lowers = bin_boundaries[:-1]
bin_uppers = bin_boundaries[1:]


msp, predictions = torch.max(softmax, 1)
correctness = predictions.eq(label)

C:\Users\10520\AppData\Local\Temp\ipykernel_15492\1828924411.py:14: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  softmax = F.softmax(output)
C:\Users\10520\AppData\Local\Temp\ipykernel_15492\1828924411.py:16: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  softmax = torch.tensor(softmax)
C:\Users\10520\AppData\Local\Temp\ipykernel_15492\1828924411.py:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  label = torch.tensor(label)


In [8]:
softmax.shape

torch.Size([16, 10])

In [9]:
msp, predictions = torch.max(softmax, 1)
correctness = predictions.eq(label)

In [11]:
predictions

tensor([3, 3, 0, 8, 8, 4, 3, 8, 3, 5, 3, 0, 3, 3, 1, 7], device='cuda:0')

In [12]:
correctness

tensor([False, False, False, False,  True, False, False, False,  True,  True,
         True, False,  True, False,  True,  True], device='cuda:0')

In [ ]:
ece = torch.zeros(1)
for bin_lower, bin_upper in zip(bin_lowers, bin_uppers):
    in_bin = msp.gt(bin_lower.item()) * msp.le(bin_upper.item())
    prop_in_bin = in_bin.float().mean()
    if prop_in_bin.item() > 0:
        accuracy_in_bin = correctness[in_bin].float().mean()
        avg_confidence_in_bin = msp[in_bin].mean()
        ece += torch.abs(avg_confidence_in_bin - accuracy_in_bin) * prop_in_bin

In [21]:
msp

tensor([0.4038, 0.4450, 0.5139, 0.6459, 0.6610, 0.5852, 0.2832, 0.5161, 0.6506,
        0.4779, 0.5202, 0.2410, 0.6307, 0.4197, 0.2250, 0.3273],
       device='cuda:0')

In [22]:
bin_lower = bin_lowers[8]
bin_upper = bin_uppers[8]
in_bin = msp.gt(bin_lower.item()) * msp.le(bin_upper.item())

In [23]:
in_bin.float().mean()

tensor(0.0625, device='cuda:0')

In [24]:
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
y = torch.tensor(x)

C:\Users\10520\AppData\Local\Temp\ipykernel_15492\1160926177.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(x)


In [6]:
import json
metrics_data = [
    {
        "conversation": [
            {
                "model": 1
                }           
        ]
    }
]




# Path to save the JSON file
file_path = 'test.json'

with open(file_path, "r") as json_file:
    data = json.load(json_file)
    print(data)

# data.append(metrics_data)
metrics_data.append(data)

# Saving the metrics data to a JSON file
with open(file_path, "w") as json_file:
    json.dump(metrics_data, json_file)
    print("Metrics data saved to", file_path)

[{'conversation': [{'model': 1}]}, [{'conversation': [{'model': 1}]}, {'conversation': [{'model': 1}]}]]
Metrics data saved to test.json


In [1]:
import torch

mdel_dict = torch.load('D:\CASIA\code_cc_misd\checkpoint\_epoch_200.pt')
print(mdel_dict.keys())

odict_keys(['conv1.weight', 'bn1.weight', 'bn1.bias', 'bn1.running_mean', 'bn1.running_var', 'bn1.num_batches_tracked', 'layer1.0.conv1.weight', 'layer1.0.bn1.weight', 'layer1.0.bn1.bias', 'layer1.0.bn1.running_mean', 'layer1.0.bn1.running_var', 'layer1.0.bn1.num_batches_tracked', 'layer1.0.conv2.weight', 'layer1.0.bn2.weight', 'layer1.0.bn2.bias', 'layer1.0.bn2.running_mean', 'layer1.0.bn2.running_var', 'layer1.0.bn2.num_batches_tracked', 'layer1.1.conv1.weight', 'layer1.1.bn1.weight', 'layer1.1.bn1.bias', 'layer1.1.bn1.running_mean', 'layer1.1.bn1.running_var', 'layer1.1.bn1.num_batches_tracked', 'layer1.1.conv2.weight', 'layer1.1.bn2.weight', 'layer1.1.bn2.bias', 'layer1.1.bn2.running_mean', 'layer1.1.bn2.running_var', 'layer1.1.bn2.num_batches_tracked', 'layer2.0.conv1.weight', 'layer2.0.bn1.weight', 'layer2.0.bn1.bias', 'layer2.0.bn1.running_mean', 'layer2.0.bn1.running_var', 'layer2.0.bn1.num_batches_tracked', 'layer2.0.conv2.weight', 'layer2.0.bn2.weight', 'layer2.0.bn2.bias', '

In [2]:
import models.model as model

net = model.ResNet18()
print(net)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (shortcut): Sequential()
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=

In [ ]:
from data.dataset import *
import torch
from torchvision.datasets import CIFAR100
class CIFAR100_loss(CIFAR100):
    def __init__(
        self,
        root: str,
        train: bool = True,
        transform: Optional[Callable] = None,
        target_transform: Optional[Callable] = None,
        download: bool = False,
        loss_dir : str = None,
        cut_rate: float = 0.0,
    ) -> None:

        super().__init__(root, transform=transform, target_transform=target_transform)
        
        self.losses = None
        if loss_dir is not None:
            self.losses = []
            with open(loss_dir, 'rb') as f:
                self.losses = pickle.load(f)
        
            if cut_rate > 0:
                # cut the loss by the value of loss, drop the least loss
                print('use cut_rate: ', cut_rate)
                loss_sort = np.sort(self.losses)
                cut_index = int(len(loss_sort) * cut_rate)
                self.save_index = [self.losses.index(value) for value in loss_sort[cut_index:]]
                self._refresh_data()
                
    def _refresh_data(self):
        self.data = [self.data[i] for i in self.save_index]
        self.targets = [self.targets[i] for i in self.save_index]
        # if self.losses is not None:
        self.losses = [self.losses[i] for i in self.save_index]
        
        print('refresh data', len(self.data), len(self.targets), len(self.losses))
                
            
    
    def __getitem__(self, index: int) -> Tuple[Any, Any]:
        """
        Args:
            index (int): Index

        Returns:
            tuple: (image, target, loss) where target is index of the target class.
        """
        
        img, target = self.data[index], self.targets[index]

        img = Image.fromarray(img)
        # img.save('./temp.jpg')
        # print('save img', img.size, img.mode, target)
        # doing this so that it is consistent with all other datasets
        # to return a PIL Image
        # img = Image.fromarray(img)

        if self.transform is not None:
            img = self.transform(img)
        # print('target', target)
        if self.target_transform is not None:
            target = self.target_transform(target)
            # print('target', target)
        if self.losses is not None:
            loss = self.losses[index]

            return img, target, loss
        else:
            return img, target